### ISSUE TITLE
Removing dependence of SM lib from the Makefile

### ISSUE THREAD

**Issue by cartilage-ftw** [MingjieJian/moog_nosm#1]
First off, thank you so much for creating this repository. I'm a student who wasn't able to obtain a license for SM and this proved to be a life-saver for my summer research.

I'm using a 64-bit Linux machine (Manjaro) and so I used the ```.rh64``` makefile. I got a compiler error which implied that it couldn't find SM libs. I fixed it by commenting out

```bash
SMLIB = /astro/apps6/opt/sm-2.4.35/lib
```
and
``` -L$(SMLIB) -lplotsub -ldevices -lutils``` in the Makefile.
Just to make sure others don't stumble on the same thing, could you add this to the README?

**Comment by MingjieJian** [comment]
Hi,

Thank you for the issue. This is actually an "old" repo and I have switched to another repo [(pymoog)](https://github.com/MingjieJian/pymoog) for using MOOG in python. It provides some functions for using MOOG easily, so I recommend also checking this repo. This issue has been fixed in pymoog, but I will modify this repo soon.

**Comment by MingjieJian** [comment]
This issue is fixed by b7599fe4c98317bd866cfde8f7e9933bf9524b39. The code should work but I recommend to try installing it again for a test.

**Comment by cartilage-ftw** [comment]
Hi,

PyMOOG looks great and will definitely give it a try at some point. I just thought it wasn't complete, but apparently it should do all the tasks the code on this repository (MOOG without SM) does? Thank you again for pointing out.

I will try the new commit and let you know the result, though it does look like it should fix it.

**Comment by MingjieJian** [comment]
Yes, not all the drivers are available in pymoog, though moog_nosm included. Thank you for the comment on the make file, and feel free to reopen it if you need.
